# Configure app
DEBUG = True
SECRET_KEY = 'REPLACE THIS WITH SOMETHING SUPER SECRET FOR PRODUCTION'

SQLALCHEMY_DATABASE_URI = 'sqlite:///item_catalog.db'
SQLALCHEMY_TRACK_MODIFICATIONS = False

JWT_TOKEN_LOCATION = ['cookies']
JWT_COOKIE_SECURE = False  # Set to True in production
JWT_ACCESS_COOKIE_PATH = '/api/'
JWT_ACCESS_CSRF_COOKIE_PATH = '/'
JWT_REFRESH_COOKIE_PATH = '/token/refresh'
JWT_REFRESH_CSRF_COOKIE_PATH = '/'
JWT_COOKIE_SAMESITE = 'Strict'
JWT_COOKIE_CSRF_PROTECT = True
JWT_SECRET_KEY = 'REPLACE THIS WITH SOMETHING SUPER SECRET FOR PRODUCTION'

# TODO Insert Google Client ID and Secret
GOOGLE_CLIENT_ID = 'INSERT GOOGLE CLIENT ID HERE'  # noqa
GOOGLE_CLIENT_SECRET = "INSERT GOOGLE CLIENT SECRET HERE"

# TODO Insert Facebook App ID and Secret
FACEBOOK_APP_ID = 'INSERT FACEBOOK APP ID HERE'
FACEBOOK_APP_SECRET = 'ISERT FACEBOOK APP SECRET HERE'

JSON_SORT_KEYS = False
